# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      astro-dependencies:
        # group astro related dependencies in one PR
        applies-to: version-updates
        patterns:
          - "*astro*"
      other-dependencies:
        # group other dependencies in one PR
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "*astro*"
    open-pull-requests-limit: 5
    versioning-strategy: "auto"
    commit-message:
      prefix: "chore"
